apiVersion: v1
kind: Service
metadata:
    name: "demo-ba16"
    labels:
        app: "demo-ba16"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "demo-ba16"